import Head from 'next/head'
import Header from '@/components/Header';
import CursorSelection from '@/components/CursorSelection';

export default function Home() {
  return (
    <>
      <Head>
        <title>Alan Yao</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* <Header /> */}
      <CursorSelection />
    </>
  )
}
